set nocompatible	                    " Use Vim defaults (much better!)

call plug#begin('~/.vim/plugged')

    " Plug 'https://github.com/tpope/vim-commentary.git'
    Plug 'https://github.com/tomtom/tcomment_vim.git'
    Plug 'itchyny/lightline.vim'
    Plug 'ctrlpvim/ctrlp.vim'
    Plug 'sjl/badwolf'
    Plug 'https://github.com/terryma/vim-multiple-cursors'
    Plug 'https://github.com/tpope/vim-surround'
    Plug 'https://github.com/scrooloose/nerdtree'

call plug#end()

" return to the file last position
" Tell vim to remember certain things when we exit
" "  '10  :  marks will be remembered for up to 10 previously edited files
" "  "100 :  will save up to 100 lines for each register
" "  :20  :  up to 20 lines of command-line history will be remembered
" "  %    :  saves and restores the buffer list
" "  n... :  where to save the viminfo files
set viminfo='10,\"100,:20,%,n~/.viminfo

function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END

:au     BufWritePost                .vimrc   	    so ~/.vimrc

let mapleader = "\\" 

map <leader>\ :q<cr>
map <leader>w :w<cr>
map <C-o> :NERDTreeToggle<CR>

